# Generated by Django 5.2.5 on 2025-08-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE book ADD COLUMN PublicationDate DATE NULL;",
            reverse_sql="ALTER TABLE book DROP COLUMN PublicationDate;"
        ),
    ]
